name: 'web_api_demo构建'
timeout: '900'
on:
  push:
    branches:
      master
jobs:
  执行构建:
    runs-on: ubuntu-latest
    steps:
      - name: '拉取代码'
        uses: 'actions/checkout@v2'
      - name: 'tar打包'
        run: mkdir -p package;tar -zcvf $package_path ./* --exclude=package

