name: 'web_api_demo构建'
on:
  push:
    branches:
      master
env:
  package_path: './package/web_api_demo.tar.gz'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: '打印全部内置变量'
        run: echo $github
      - name: '拉取代码'
        uses: 'actions/checkout@v2'
      - name: 'tar打包'
        run: mkdir -p package;tar --exclude=package -zcvf  $package_path ./*

